version: '3.8'
services:
  app:
    image: moses12345/rotary:v1
    # build: .
    ports:
      - '5000:5000'
    depends_on:
      - mysql-db
    environment:
      - MYSQL_HOST=process.env.DB_HOST
      - MYSQL_USER=process.env.DB_USER
      - MYSQL_PASSWORD=process.env.DB_PASSWORD
      - MYSQL_DATABASE=process.env.DATABASE

  mysql-db:
    image: mysql:latest
    # container_name: rotary-mysql-container
    restart: always
    environment:
      - MYSQL_HOST=process.env.DB_HOST
      - MYSQL_ROOT_PASSWORD=process.env.DB_PASSWORD
      - MYSQL_USER=process.env.DB_USER
      - MYSQL_PASSWORD=process.env.DB_PASSWORD
      - MYSQL_DATABASE=process.env.DATABASE
    ports:
      - '3307:3306'
    volumes:
      - /home/moses/Desktop/mysql_storage:/var/lib/mysql
